import { z } from 'zod';
import { TipoAccion } from '../enums';

export const AccionSchema = z.object({
  id: z.string().cuid(),
  estudioId: z.string().cuid(),
  casoId: z.string().cuid(),
  tipo: z.nativeEnum(TipoAccion),
  descripcionTecnica: z.string().min(10).max(2000),
  descripcionCliente: z.string().min(10).max(2000),
  proximoPaso: z.string().max(500).nullable(),
  visibleCliente: z.boolean(),
  registradoPorId: z.string().cuid(),
  creadoEn: z.date(),
});

export type Accion = z.infer<typeof AccionSchema>;

export const AccionCreateSchema = z.object({
  casoId: z.string().cuid(),
  tipo: z.nativeEnum(TipoAccion),
  descripcionTecnica: z.string().min(10).max(2000),
  descripcionCliente: z.string().min(10).max(2000).optional(), // Generated by AI if not provided
  proximoPaso: z.string().max(500).optional(),
  visibleCliente: z.boolean().default(true),
});

export type AccionCreate = z.infer<typeof AccionCreateSchema>;
